---
- hosts: localhost
  gather_facts: False

  roles:
  - openshift_python

  tasks:

  - name: Set a fact to be used in script
    set_fact:
      op_types: "pods"


  - name: Run sample
    openshift_python:
      project: 'default'

      vars:
        some_var_name: 'abc'
        another: 5

      script: |
        print('You can use an arg: {} and {}'.format(vars['some_var_name'], vars['another']))

        # This example shows use of ansible facts
        new_facts.pods = oc.selector("{{op_types}}").qnames()

    register: result

  - name: Show result
    debug:
      msg: "{{result}}"

  - name: Show new_facts
    debug:
      msg: "{{pods}}"
